### ISSUE TITLE
Protozoa demo broken due to incorrect smoothstep usage

### ISSUE THREAD

**Issue by mrdoob** [boytchev/tsl-textures#6]
<img width="529" alt="Screenshot 2024-11-23 at 11 02 11" src="https://github.com/user-attachments/assets/125cd87e-bb6e-43e4-95f9-d0b971bb3cbb">

**Comment by boytchev** [comment]
Thanks for the info. I'm not quite sure why it did work in the past. It should be fixed. Does it work for you now?

The npm package is not updated as the npmjs.com is doing some maintenance now and package publishing is temporarily unavailable.
